import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import localFont from "next/font/local";


const gilroy = localFont({
  src: "fonts/Gilroy-Bold.ttf",
  variable: "--gilroy",
});
const Monument = localFont({
  src: "fonts/MonumentExtended-Regular.ttf",
  variable: "--monument",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Monument.variable} ${gilroy.variable} antialiased`}
      >
        
          <Layout>{children}</Layout>
        
      </body>
    </html>
  );
}
